//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNewsWindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Views = new HashSet<View>();
        }
    
        public int NewsID { get; set; }
        public string NewsTitle { get; set; }
        public string Source { get; set; }
        public string NewsDescription { get; set; }
        public string Genre { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string ImageInNews { get; set; }
    
        public virtual ICollection<View> Views { get; set; }
    }
}
