/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boolean_Retrieval_Model_IR;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author K163618
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        term1query = new javax.swing.JLabel();
        RunButton = new javax.swing.JButton();
        Term1field = new javax.swing.JTextField();
        Notterm1 = new javax.swing.JRadioButton();
        term2field = new javax.swing.JTextField();
        Notterm2 = new javax.swing.JRadioButton();
        term3field = new javax.swing.JTextField();
        Notterm3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Operation1comboBox = new javax.swing.JComboBox<>();
        Operation2comboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        term1query.setText("Term#1");

        RunButton.setText("Run");
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        Term1field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Term1fieldActionPerformed(evt);
            }
        });

        Notterm1.setText("Not");
        Notterm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notterm1ActionPerformed(evt);
            }
        });

        term2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                term2fieldActionPerformed(evt);
            }
        });

        Notterm2.setText("Not");
        Notterm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notterm2ActionPerformed(evt);
            }
        });

        term3field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                term3fieldActionPerformed(evt);
            }
        });

        Notterm3.setText("Not");
        Notterm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notterm3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Term#2");

        jLabel2.setText("Terrm#3");

        Operation1comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "and", "or" }));

        Operation2comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "and", "or" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(term1query, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(term2field, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Term1field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                                    .addComponent(term3field, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(Operation2comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Notterm3)
                            .addComponent(Notterm1)
                            .addComponent(Notterm2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(RunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(Operation1comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(term1query)
                    .addComponent(Term1field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Notterm1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Operation1comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(term2field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Notterm2))
                .addGap(13, 13, 13)
                .addComponent(Operation2comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(term3field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Notterm3))
                .addGap(18, 18, 18)
                .addComponent(RunButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String term1,term2,term3,operation1,operation2;
    boolean not1,not2,not3;
    
    
    Boolean_Retrieval_Model_IR obj = new Boolean_Retrieval_Model_IR();
    
   
    private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed
        // TODO add your handling code here:
        
        term1= Term1field.getText();
        not1=Notterm1.isSelected();            
        
        term2= term2field.getText();
        not2=Notterm2.isSelected(); 
        
        term3= term3field.getText();
        not3=Notterm3.isSelected(); 
        
        operation1= Operation1comboBox.getSelectedItem().toString();
        operation2= Operation2comboBox.getSelectedItem().toString();
        
        
        try {
            obj.search();
        } catch (IOException ex) {
            Logger.getLogger(homePage.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_RunButtonActionPerformed

    private void Term1fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Term1fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Term1fieldActionPerformed

    private void Notterm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notterm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Notterm1ActionPerformed

    private void Notterm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notterm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Notterm2ActionPerformed

    private void term2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_term2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_term2fieldActionPerformed

    private void term3fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_term3fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_term3fieldActionPerformed

    private void Notterm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notterm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Notterm3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Notterm1;
    private javax.swing.JRadioButton Notterm2;
    private javax.swing.JRadioButton Notterm3;
    private javax.swing.JComboBox<String> Operation1comboBox;
    private javax.swing.JComboBox<String> Operation2comboBox;
    private javax.swing.JButton RunButton;
    private javax.swing.JTextField Term1field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel term1query;
    private javax.swing.JTextField term2field;
    private javax.swing.JTextField term3field;
    // End of variables declaration//GEN-END:variables
}
